### ISSUE TITLE
Tests are failing on Travis CI

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/CDSAPI.jl#30]
https://travis-ci.org/github/JuliaClimate/CDSAPI.jl

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I will try looking through the stack trace and figure out what is causing this issue.

**Comment by LakshyaKhatri** [comment]
Okay, so in build for  `Julia: 1.4` I saw this [error](https://travis-ci.org/github/JuliaClimate/CDSAPI.jl/jobs/709644554#L302):
```julia
SystemError: opening file "/home/travis/.cdsapirc": No such file or directory
```
This is because we are looking for API keys from `.cdsapirc` file in the `retrieve()` method.
We can fix this by setting up API keys on Travis environment (something like storing keys in `.cdsapirc` and then encrypting them, as we do in GitHub secrets).
I am not sure about what's the right way of doing this, but I am on it.

I will try to post a solution for `Julia: 1.4` first and then I will target the lower versions.

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, one solution I found is encrypting `.cdsapirc` file using Travis command line tool and then uploading the generated encrypted file `.cdsapi.enc` to GitHub (see: [Secret Files](https://docs.travis-ci.com/user/encrypting-files/)). After that, adding commands to `.travis.yml` to decrypt the file in the specified location before running the test jobs.

**Comment by juliohm** [comment]
Nice @LakshyaKhatri , I am not the most experienced with GitHub and keys, but I appreciate if you can document in the issue the process you took so that future contributors can reproduce in case the secret file gets outdated.

Thank you for the great work, it is really nice to see the package evolving.

**Comment by LakshyaKhatri** [comment]
Should I document the process in this issue itself?

**Comment by juliohm** [comment]
That would be nice. Thanks for doing it.

**Comment by LakshyaKhatri** [comment]
## (Julia: 1.4) Error: 
SystemError: opening file "/home/travis/.cdsapirc": No such file or directory

## Problem:
The file `.cdsapirc` contains the API keys that we use to fetch data from the CDS website. Since the file contains sensitive information it is kept outside from the git tracking directory. A standard is to keep the run command (`rc`) files in the `HOME` directory. Now, since the file is not getting tracked by git, it is also not getting uploaded to Travis CI. Hence, when the `retrieve()` function is called it looks for the `.cdsapirc` file in the `HOME` directory and complains when the file is not found.

## Solution:
There can be many possible solutions. One which I found is:
 - Encrypting the `.cdsapirc` file using Travis CI Command-Line Client.
 - Adding the encrypted `.cdsapi.enc` file to GitHub.
 - Adding instructions to `.travis.yml` to tell Travis CI that it has to decrypt the file before running the build.

## Implementation
 - Create a file `.cdsapirc` in the `HOME` directory with the following contents:

```rc
url: https://cds.climate.copernicus.eu/api/v2
key: <cds-apikey-for-travis>
```
- Install Travis CI Command-Line Client.
- Log in to travis using:
```bash
travis login
```
- Encrypt `.cdsapirc` file:
```bash
travis encrypt-file -r path/to/CDSAPI/Repo $HOME/.cdsapirc --add
```
This will encrypt the `.cdsapirc` file and add decryption command to your `.travis.yml` automatically, which will look something like this:
```yml
before_install:
 - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .cdsapirc.enc -out ~\/.cdsapirc -d
```
But Travis will complain that there is no directory matching `~/`.
 - Update the decrypted file path in `.travis.yml`. In other words, change this:
```yml
before_install:
 - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .cdsapirc.enc -out ~\/.cdsapirc -d
```
To this:
```yml
before_install:
 - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .cdsapirc.enc -out $HOME\/.cdsapirc -d
```
***Note:** Encrypting the file again will generate new public keys for Travis.*

 - This will allow `retrieve()` to use API keys from a `.cdsapirc` file and will resolve the issue.
---

PS: I am going through the error log to check what is the issue in other versions and will soon post solutions to fix them too.

**Comment by juliohm** [comment]
Such an amazing work @LakshyaKhatri , thank you for improving the package, very professional report. Is the issue solved now in Travis CI Julia v1.4?

**Comment by LakshyaKhatri** [comment]
Yes :smile: :
![Screenshot from 2020-07-20 20-23-40](https://user-images.githubusercontent.com/28972442/87952019-eefb3f80-cac6-11ea-9abf-4bf3042f3bd5.png)

**Comment by juliohm** [comment]
Could you please submit a PR @LakshyaKhatri to implement the changes in the .travis.yml? I wonder how the tests are passing on Travis without the commands you shared above in the .travis.yml file?

**Comment by LakshyaKhatri** [comment]
Hello @juliohm, I tried to figure out the build issues for Julia 1.0, 1.1 and 1.2. It is the same dependency issue in all of them:
```bash
ERROR: Unsatisfiable requirements detected for package eccodes_jll [b04048ba]:
 eccodes_jll [b04048ba] log:
 ├─possible versions are: [2.17.0, 2.18.0] or uninstalled
 ├─restricted by compatibility requirements with GRIB [b16dfd50] to versions: [2.17.0, 2.18.0]
 │ └─GRIB [b16dfd50] log:
 │   ├─possible versions are: 0.2.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.2.0
 └─restricted by compatibility requirements with libpng_jll [b53b4c65] to versions: uninstalled — no versions left
   └─libpng_jll [b53b4c65] log:
     ├─possible versions are: 1.6.37 or uninstalled
     └─restricted by julia compatibility requirements to versions: uninstalled
```

I searched a lot and my best hunch is that it is causing because GRIB is using version 2.18.0 (which is released 13 days ago) for `eccodes_jll` but the minimum available version for `eccodes_jll` is 2.17.0 (see [GRIB.jl/Manifest.toml](https://github.com/weech/GRIB.jl/blob/master/Manifest.toml#L96-L100)).

I might need some help in this one.

**Comment by juliohm** [comment]
Thank you @LakshyaKhatri for the update. I think we can support Julia v1.4 and later versions. For simplicity, let's drop support for lower versions in our .travis.yml and add `julia = 1.4` to our Project.toml. Could you please work on that? :)

**Comment by LakshyaKhatri** [comment]
Thanks for the help @juliohm, are we considering adding Julia 1.3 too (since the errors are fixed in #34) ?

**Comment by juliohm** [comment]
Nice, if the tests are passing for Julia 1.3 without eccodes_jll issues, let's add it as well :+1:

**Comment by LakshyaKhatri** [comment]
Okay, I will check and make changes accordingly. :)
